### PR TITLE
Feature/update storybook

### PR DESCRIPTION
**Pull request by wps13**
**What**: Add knobs for the stories

**Why**: With knobs, it's possible to modify the parameters for the components in the live version, 

**How**: Add the knobs inside the stories, add variables to color and state, using a label and giving a default value.

### CODE REVIEW

**Comment by jameswlane** [comment]
@wps13 Let me know if I need to adjust the Codacy bot code listing rules.

**Comment by jameswlane** [comment]
@wps13 Also I would add `storybook-static` folder to the `.gitignore` that should resolve most the issues you are seeing.

**Comment by jameswlane** [comment]
@wps13 I was able to edit the `.gitignore` and delete the static folder via the browser on my phone (Yeah GitHub). That should resolve a number of the issues. Hopefully this helped.

**Comment by jameswlane** [comment]
@wps13 I think we can fix the rest of the issues if we pull down the code and run `nvm run eslint:fix` and push it back up.

**Comment by wps13** [comment]
@jameswlane  I was updating the testing library, so i will run the eslint here to fix it. Thanks for the help!

**Comment by jameswlane** [comment]
@wps13 if this is complete I wouldn’t worry about the rest of the errors from Code Climate and Codacy. Just merge it in, the errors are code duplication and no return types for the examples. 

I need to change the settings to not require return types for the stories and ignore code duplication for the examples.

**Comment by jameswlane** [comment]
@wps13 This is pretty awesome, thank you for all your help with getting the example site back up and running and improving it. 🎉  It is very appreciated 👍

**Comment by wps13** [comment]
@jameswlane Sorry for the causing so many problems. Finished fix the major problems, but still can't pass codeclimate because it's complaining about similar code, but this code is the one used for the knobs, so they should be similar.

**Pull request closed without merging**
