### PR TITLE
Feature/move dependencies 

### LINKED ISSUE #615: Move @emotion/core to Peer Dependencies

### PR DESCRIPTION
**Pull request by Larissagilliane**
**What**: Move @emotion/core to Peer Dependencies

**Why**: These changes are requested at issue #615  

**How**: I moved the '@emotion/core' to 'peerDependencies' in package.json file.

Closes #615

### CODE REVIEW

**Comment by jameswlane** [comment]
@Larissagilliane I will be digging into this today.

**Comment by jameswlane** [comment]
@Larissagilliane Since we moved `@emotion/core` as a peer dependency Rollup is throwing a error that’s what’s breaking our build. We may need to add some tweaks to the rollup config to allow emotion to be a external dependency.

**Comment by Larissagilliane** [comment]
@jameswlane  i've made some alterations on x file, if the problem still persist you can please notify me

**Comment by jameswlane** [comment]
@Larissagilliane Everything looks good, if you can fix the merge conflict I will merge this also.

**Pull request merged**
