### PR TITLE
Restore storybook files

### PR DESCRIPTION
**Pull request by Larissagilliane**
**What**:  Restore the storybook for new tests.

**Why**: The storybook is really helpful to developers see and test new features, it helps to turn faster the development proceedures.

**How**: Restorying the previous storybook, updated previously by @wps13 .

### CODE REVIEW

**Comment by jameswlane** [comment]
@Larissagilliane I will be digging into this today.

**Comment by jameswlane** [comment]
@Larissagilliane The build is failing due to two items we need to resolve.

@codacy-bot detected multiple lines in the end of `stories/ball.stories.tsx`

And when now try’s to deploy it is looking for storybook to be in the directory  `public` not `storybook-static`

This should resolve everything and it should deploy without a issue.

**Comment by Larissagilliane** [comment]
@jameswlane  i'm still fixing the problems with `storybook-static` folder, soon as i fixed i'll commit.

**Comment by Larissagilliane** [comment]
@jameswlane  i've made the corrections and finally the changes were approved

**Pull request merged**
