### PR TITLE
Bug/ballgridpulse animation

### LINKED ISSUE #439: BallGridPulse animation is broken.
**Describe the bug**
When using `BallGridPulse` there is no animation.

### PR DESCRIPTION
**Pull request by Larissagilliane**
**What**: "BallGridPulse" animation fixed.

**Why**: These corrections are requested at issue #439 .

**How**: Problably this animation was previosly implemented, but for some reason the code was comented. I made some adjustments and adapted the tests cases.

Closes #439

### CODE REVIEW

**Comment by Larissagilliane** [comment]
I had to use the storybook created at pull request "Restore storybook files", to test the loader and certificate myself that he is working correctly.

**Comment by jameswlane** [comment]
@Larissagilliane I will be digging into this today.

**Comment by jameswlane** [comment]
@Larissagilliane  this is failing for the same reason as the storybook pr its looking for a public directory.

**Comment by Larissagilliane** [comment]
@jameswlane  problem solved

**Pull request merged**
